import time
print("hello another useless person ")
time.sleep(1)
print("welcome to my shit code")
a = input("do you want to see the output yes/no ")
if a == "yes" :
    print("H")
    time.sleep(1)
    print("E")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("O")
    time.sleep(1)
    print("W")
    time.sleep(1)
    print("O")
    time.sleep(1)
    print("R")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("D")
if a == "Yes" :
    print("H")
    time.sleep(1)
    print("E")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("O")
    time.sleep(1)
    print("W")
    time.sleep(1)
    print("O")
    time.sleep(1)
    print("R")
    time.sleep(1)
    print("L")
    time.sleep(1)
    print("D")
if a == "no" :
    print("WTF why did you came here then go shake you pp")
if a == "No":
    print("WTF why did you came here then go shake you pp")
else :
    print("cant you just type a fricking yes or no ")
